#!/usr/bin/env python

# This file is for building as a Godot engine module.

Import("env")
Import("env_modules")

env_modules.Append(CPPDEFINES=["GODOT_MODULE"])

env_hyperbolic3d = env_modules.Clone()

env_hyperbolic3d.add_source_files(env.modules_sources, "*.cpp")
env_hyperbolic3d.add_source_files(env.modules_sources, "math/*.cpp")
env_hyperbolic3d.add_source_files(env.modules_sources, "nodes/*.cpp")

if env.editor_build:
    # If your module has editor-specific code, you can add it here.
    # env_hyperbolic3d.add_source_files(env.modules_sources, "editor/*.cpp")
    pass
